Repository oasis-tcs/openeox, pull requests merged in 2025-04, with the labels that each got.

#84 Meeting Minutes 2025 into correct folder
  meeting-minutes/2025/2025-01-15.md
  meeting-minutes/2025/2025-02-19.md
Labels: meeting minutes

#75 General Availability Definition
  definitions-taxonomy/GA.md
Labels: motion_passed

#80 Updating End-of-Sales.md
  definitions-taxonomy/End-of-Sales.md
Labels: motion

#78 Adding Product Definition
  definitions-taxonomy/Product.md
Labels: motion

#83 Minor update to End-of-Life.md
  definitions-taxonomy/End-of-Life.md
Labels: editorial

#81 Updating Product Lifecycle Definition
  definitions-taxonomy/Product-Lifecycle.md
Labels: motion_passed

#73 Adding the End of Security Support Definition
  definitions-taxonomy/End-of-Security-Support.md
Labels: motion_passed
